"""
Enterprise Context Brain (ECB) v2.1 - Synthetic Enterprise Fixtures
Comprehensive realistic dataset for Project Aegis and Project Orion,
including Jira tickets, Git commits, ADR decisions, Risks, 5 Memory Types,
known contradictions/conflicts, and governance actions.
"""

from datetime import datetime, timedelta
from typing import Dict, List, Any
from ...domain.schemas import (
    Organization,
    User,
    Source,
    SourceType,
    AuthorityLevel,
    SourceRecord,
    Evidence,
    MemoryItem,
    MemoryType,
    Project,
    ProjectStatus,
    Milestone,
    Risk,
    RiskSeverity,
    RiskStatus,
    Decision,
    DecisionStatus,
    ActionPreview,
    RiskClass,
    ActionStatus,
    AgentWorkflow,
    AuditEvent,
)


def generate_fixtures() -> Dict[str, Any]:
    now = datetime.utcnow()
    day_ago = lambda days: now - timedelta(days=days)
    hours_ago = lambda hours: now - timedelta(hours=hours)

    # 1. Organizations
    org = Organization(
        id="org-acme-fintech",
        name="Acme Global Financial Technologies",
        policy_profile="enterprise_strict",
        created_at=day_ago(180),
    )

    # 2. Users
    users = [
        User(
            id="usr-sarah-jenkins",
            email="sarah.jenkins@acmefin.com",
            name="Sarah Jenkins",
            role="project_manager",
            org_id=org.id,
        ),
        User(
            id="usr-alex-mercer",
            email="alex.mercer@acmefin.com",
            name="Alex Mercer",
            role="engineering_lead",
            org_id=org.id,
        ),
        User(
            id="usr-marcus-chen",
            email="marcus.chen@acmefin.com",
            name="Marcus Chen",
            role="vp_engineering",
            org_id=org.id,
        ),
        User(
            id="usr-elena-rostova",
            email="elena.rostova@acmefin.com",
            name="Elena Rostova",
            role="risk_officer",
            org_id=org.id,
        ),
    ]

    # 3. Sources
    sources = [
        Source(
            id="src-jira-aegis",
            org_id=org.id,
            type=SourceType.JIRA,
            name="Jira - Global Payments Modernization",
            authority=AuthorityLevel.HIGH,
            is_connected=True,
            last_synced_at=hours_ago(1),
            config={"base_url": "https://jira.acmefin.internal/projects/AEGIS"},
        ),
        Source(
            id="src-git-aegis",
            org_id=org.id,
            type=SourceType.GIT,
            name="GitHub - acmefin/payments-core",
            authority=AuthorityLevel.HIGH,
            is_connected=True,
            last_synced_at=hours_ago(2),
            config={"repo": "acmefin/payments-core", "default_branch": "main"},
        ),
        Source(
            id="src-adr-docs",
            org_id=org.id,
            type=SourceType.ADR,
            name="Architecture Decision Records",
            authority=AuthorityLevel.HIGH,
            is_connected=True,
            last_synced_at=hours_ago(4),
            config={"path": "docs/architecture/decisions/"},
        ),
        Source(
            id="src-slack-payments",
            org_id=org.id,
            type=SourceType.SLACK,
            name="Slack #payments-architecture",
            authority=AuthorityLevel.MEDIUM,
            is_connected=True,
            last_synced_at=hours_ago(1),
            config={"channel": "C05PAYMENTS"},
        ),
    ]

    # 4. Projects
    projects = [
        Project(
            id="prj-aegis",
            org_id=org.id,
            name="Project Aegis - Global Payments Modernization",
            code="AEGIS",
            description="Core payment processing modernization migrating from legacy batch settlement to distributed real-time event-driven ledger with sub-50ms SLA and PCI-DSS 4.0 certification.",
            status=ProjectStatus.DELAYED,
            health_score=68,
            owner_id="usr-sarah-jenkins",
            owner_name="Sarah Jenkins",
            target_completion_date=day_ago(-68), # Target Oct 30, 2026
            estimated_delay_days=45,
            created_at=day_ago(120),
            updated_at=hours_ago(2),
            active_risks_count=3,
            open_tickets_count=18,
            recent_decisions_count=3,
            milestones=[
                Milestone(
                    id="m-aegis-1",
                    project_id="prj-aegis",
                    name="Core Payment Engine Migration",
                    target_date=day_ago(45),
                    status="completed",
                    progress_percentage=100,
                ),
                Milestone(
                    id="m-aegis-2",
                    project_id="prj-aegis",
                    name="Distributed Kafka Event Bus & CDC Pipeline",
                    target_date=day_ago(10),
                    status="delayed",
                    progress_percentage=75,
                    blocker_description="Consumer group rebalancing causing partition lag under peak TPS (AEGIS-108).",
                ),
                Milestone(
                    id="m-aegis-3",
                    project_id="prj-aegis",
                    name="PCI-DSS 4.0 Compliance Sign-off & Tokenization Gateway",
                    target_date=day_ago(-30),
                    status="at_risk",
                    progress_percentage=40,
                    blocker_description="Pending final external security auditor assessment scheduled for late September.",
                ),
                Milestone(
                    id="m-aegis-4",
                    project_id="prj-aegis",
                    name="Production Traffic Cutover & Canary Ramp",
                    target_date=day_ago(-68),
                    status="delayed",
                    progress_percentage=10,
                ),
            ],
        ),
        Project(
            id="prj-orion",
            org_id=org.id,
            name="Project Orion - Core Banking Cloud Migration",
            code="ORION",
            description="Multi-region cloud infrastructure transformation migrating on-premises mainframe core banking systems to AWS managed Kubernetes and Aurora PostgreSQL.",
            status=ProjectStatus.ON_TRACK,
            health_score=92,
            owner_id="usr-alex-mercer",
            owner_name="Alex Mercer",
            target_completion_date=day_ago(-110),
            estimated_delay_days=0,
            created_at=day_ago(90),
            updated_at=hours_ago(5),
            active_risks_count=1,
            open_tickets_count=12,
            recent_decisions_count=2,
            milestones=[
                Milestone(
                    id="m-orion-1",
                    project_id="prj-orion",
                    name="AWS Infrastructure Foundation & Transit Gateway",
                    target_date=day_ago(30),
                    status="completed",
                    progress_percentage=100,
                ),
                Milestone(
                    id="m-orion-2",
                    project_id="prj-orion",
                    name="Data Layer Replication & Dual-Write Validation",
                    target_date=day_ago(-20),
                    status="in_progress",
                    progress_percentage=80,
                ),
            ],
        ),
        Project(
            id="prj-clara-v3",
            org_id=org.id,
            name="Project Clara-v3",
            code="CLARA",
            description="Clara-v3 repository integration project.",
            status=ProjectStatus.ON_TRACK,
            health_score=100,
            owner_id="usr-sarah-jenkins",
            owner_name="Sarah Jenkins",
            target_completion_date=day_ago(-30),
            estimated_delay_days=0,
            created_at=day_ago(1),
            updated_at=now,
            active_risks_count=0,
            open_tickets_count=0,
            recent_decisions_count=0,
            milestones=[],
        ),
        Project(
            id="prj-rakesh-infosrc-enterprise_context_brain-ecb-",
            org_id=org.id,
            name="Rakesh-infosrc/Enterprise_Context_Brain-ECB-",
            code="ECB",
            description="Enterprise Context Brain live repository integration project.",
            status=ProjectStatus.ON_TRACK,
            health_score=100,
            owner_id="usr-system",
            owner_name="System",
            target_completion_date=day_ago(-30),
            estimated_delay_days=0,
            created_at=day_ago(1),
            updated_at=now,
            active_risks_count=0,
            open_tickets_count=0,
            recent_decisions_count=0,
            milestones=[],
        ),
        Project(
            id="prj-rakesh-infosrc-mcp-server-airflow",
            org_id=org.id,
            name="Rakesh-infosrc/mcp-server-airflow",
            code="AIRFLOW",
            description="MCP Airflow Server integration project.",
            status=ProjectStatus.ON_TRACK,
            health_score=100,
            owner_id="usr-system",
            owner_name="System",
            target_completion_date=day_ago(-30),
            estimated_delay_days=0,
            created_at=day_ago(1),
            updated_at=now,
            active_risks_count=0,
            open_tickets_count=0,
            recent_decisions_count=0,
            milestones=[],
        ),
    ]

    # 5. Decisions (ADRs)
    decisions = [
        Decision(
            id="dec-adr-001",
            project_id="prj-aegis",
            adr_number="ADR-001",
            title="Synchronous REST APIs for Inter-Service Payment Communication",
            context="Initial architecture proposed synchronous HTTP/REST microservice communication for transaction settlement.",
            decision_summary="Adopt synchronous REST APIs between Payment Ingestion and Settlement services.",
            rationale="Fast initial prototyping and simple mental model during discovery phase.",
            status=DecisionStatus.SUPERSEDED,
            superseded_by_id="dec-adr-002",
            alternatives_considered=[
                {"name": "REST API", "tradeoff": "Simple but tight temporal coupling and cascade failure risks"},
                {"name": "gRPC", "tradeoff": "High performance but still synchronous blocking I/O"},
            ],
            consequences=[
                "Created throughput bottlenecks during synthetic stress testing (>8,000 TPS triggered timeout cascades).",
                "Violated resilience requirement for disconnected offline processing.",
            ],
            decided_by="Alex Mercer",
            decided_at=day_ago(110),
            linked_evidence_ids=["evi-adr-001-text"],
        ),
        Decision(
            id="dec-adr-002",
            project_id="prj-aegis",
            adr_number="ADR-002",
            title="Event-Driven Architecture using Apache Kafka & Schema Registry",
            context="Synchronous REST proved inadequate for 25,000 TPS peak load and multi-region resilience.",
            decision_summary="Supersede ADR-001. Migrate all inter-service payment orchestration to an asynchronous event-driven model using Apache Kafka with Avro Schema Registry.",
            rationale="Guarantees sub-50ms ingestion latency, provides append-only immutable transaction logs, and enables decoupled fraud detection and ledger accounting.",
            status=DecisionStatus.ACCEPTED,
            supersedes_id="dec-adr-001",
            alternatives_considered=[
                {"name": "RabbitMQ", "tradeoff": "Excellent AMQP routing but weaker persistent event replay capabilities at scale"},
                {"name": "Apache Pulsar", "tradeoff": "Multi-tenancy strengths but operational overhead for current SRE team"},
                {"name": "Apache Kafka", "tradeoff": "Proven enterprise scale, replayable commit log, robust ecosystem"},
            ],
            consequences=[
                "Requires careful partition key design to maintain strict per-account order.",
                "Introduced partition rebalancing operational complexity currently being addressed under AEGIS-108.",
            ],
            decided_by="Alex Mercer & Marcus Chen",
            decided_at=day_ago(75),
            linked_evidence_ids=["evi-adr-002-text", "evi-git-88f21"],
        ),
        Decision(
            id="dec-adr-003",
            project_id="prj-aegis",
            adr_number="ADR-003",
            title="Canonical Database: PostgreSQL with pgvector & Row-Level Security",
            context="Need unified enterprise context and transaction state store avoiding fragmented polyglot persistence.",
            decision_summary="Select PostgreSQL 16+ with pgvector extension as the primary canonical data store and context memory substrate.",
            rationale="ACID guarantees, mature JSONB querying, enterprise RLS security, and unified relational + semantic retrieval without requiring graph DB lock-in.",
            status=DecisionStatus.ACCEPTED,
            alternatives_considered=[
                {"name": "MongoDB + Pinecone", "tradeoff": "Dual data store overhead and eventual consistency risks"},
                {"name": "Neo4j Graph Database", "tradeoff": "Niche query language (Cypher) and higher operational footprint for MVP"},
                {"name": "PostgreSQL + pgvector", "tradeoff": "Strong consistency, unified relational context, enterprise compliance"},
            ],
            consequences=[
                "Simplified operational runbooks and unified backup/recovery strategy.",
                "Enables zero-latency correlation between canonical records and semantic embeddings.",
            ],
            decided_by="Alex Mercer",
            decided_at=day_ago(60),
            linked_evidence_ids=["evi-adr-003-text"],
        ),
    ]

    # 6. Risks
    risks = [
        Risk(
            id="rsk-aegis-01",
            project_id="prj-aegis",
            title="Kafka Consumer Group Partition Rebalance Bottleneck",
            description="Consumer group rebalancing during high traffic bursts introduces up to 1,200ms processing lag, causing downstream payment settlement timeouts.",
            severity=RiskSeverity.HIGH,
            probability=4,
            impact=4,
            score=16,
            owner="Alex Mercer",
            status=RiskStatus.MITIGATING,
            mitigation_plan="Tune consumer heartbeat (3000ms), max poll interval, and deploy static group membership (KIP-345) to eliminate stop-the-world rebalances. Tracked in AEGIS-108.",
            linked_evidence_ids=["evi-jira-108", "evi-git-92c4a"],
            identified_at=day_ago(14),
            last_reviewed_at=hours_ago(6),
        ),
        Risk(
            id="rsk-aegis-02",
            project_id="prj-aegis",
            title="PCI-DSS 4.0 Audit Compliance Sign-off Delay",
            description="External QSA auditor requested additional evidence for cardholder data encryption in Kafka topic payloads and zero-trust key rotation logs.",
            severity=RiskSeverity.CRITICAL,
            probability=4,
            impact=5,
            score=20,
            owner="Elena Rostova",
            status=RiskStatus.IDENTIFIED,
            mitigation_plan="Implement client-side field-level encryption with AWS KMS before publishing to Kafka topics. Schedule bi-weekly auditor sync. Tracked in AEGIS-112.",
            linked_evidence_ids=["evi-jira-112"],
            identified_at=day_ago(21),
            last_reviewed_at=day_ago(1),
        ),
        Risk(
            id="rsk-aegis-03",
            project_id="prj-aegis",
            title="Third-Party Payment Gateway SLA Flakiness",
            description="Acquiring bank sandbox API intermittently returns HTTP 504 during settlement reconciliation windows.",
            severity=RiskSeverity.MEDIUM,
            probability=3,
            impact=3,
            score=9,
            owner="Sarah Jenkins",
            status=RiskStatus.MONITORING,
            mitigation_plan="Implement resilient circuit breaker with exponential backoff and dead-letter queue processing.",
            linked_evidence_ids=["evi-jira-101"],
            identified_at=day_ago(35),
            last_reviewed_at=day_ago(3),
        ),
        Risk(
            id="rsk-clara-01",
            project_id="prj-clara-v3",
            title="Database Connection Pool Exhaustion under Peak Traffic",
            description="High-frequency REST queries to authentication services exhaust database connection pool, raising connection timeout exceptions.",
            severity=RiskSeverity.HIGH,
            probability=4,
            impact=4,
            score=16,
            owner="Sarah Jenkins",
            status=RiskStatus.IDENTIFIED,
            mitigation_plan="Increase connection pool size to 50 and implement gRPC connection reuse. Tracked in CLARA-101.",
            linked_evidence_ids=["evi-jira-clara-101"],
            identified_at=day_ago(5),
            last_reviewed_at=hours_ago(2),
        ),
    ]

    # 7. Source Records (Raw normalized items)
    source_records = [
        SourceRecord(
            id="rec-jira-108",
            source_id="src-jira-aegis",
            source_type=SourceType.JIRA,
            project_id="prj-aegis",
            external_id="AEGIS-108",
            title="[Bug] Consumer Group Partition Rebalance Bottleneck causing SLA breach in payment-event-bus",
            content="Under stress testing at 18,000 TPS, Kafka consumer group rebalances freeze consumption for 1.2 to 2.4 seconds. Downstream settlement engine breaches sub-50ms SLA. Assigned to Alex Mercer. Priority: P0 Critical.",
            observed_at=hours_ago(6),
            metadata={"status": "IN_PROGRESS", "priority": "CRITICAL", "assignee": "Alex Mercer", "sprint": "Sprint 24"},
            author="Alex Mercer",
        ),
        SourceRecord(
            id="rec-jira-112",
            source_id="src-jira-aegis",
            source_type=SourceType.JIRA,
            project_id="prj-aegis",
            external_id="AEGIS-112",
            title="[Task] PCI-DSS 4.0 Cardholder Data Field-Level Encryption & Tokenization",
            content="QSA auditor audit finding: cardholder PAN and CVV tokens passing through intermediate Kafka partitions require envelope encryption with KMS customer-managed keys. Blocked until encryption wrapper is deployed.",
            observed_at=day_ago(2),
            metadata={"status": "BLOCKED", "priority": "BLOCKER", "assignee": "Elena Rostova"},
            author="Elena Rostova",
        ),
        SourceRecord(
            id="rec-jira-115",
            source_id="src-jira-aegis",
            source_type=SourceType.JIRA,
            project_id="prj-aegis",
            external_id="AEGIS-115",
            title="[Epic] Project Aegis Target Launch Milestone Tracking",
            content="Project launch scheduled for September 15, 2026. All tracks on schedule for full production traffic ramp. (NOTE: Outdated roadmap entry conflicting with Git release roadmap b4e19).",
            observed_at=day_ago(25), # Stale record
            metadata={"status": "OPEN", "target_date": "2026-09-15"},
            author="Sarah Jenkins",
        ),
        SourceRecord(
            id="rec-adr-002-doc",
            source_id="src-adr-docs",
            source_type=SourceType.ADR,
            project_id="prj-aegis",
            external_id="ADR-002",
            title="ADR-002: Event-Driven Architecture using Apache Kafka & Schema Registry",
            content="Status: ACCEPTED. Supersedes ADR-001. All inter-service payment orchestration must use Apache Kafka. Decoupled ledger guarantees sub-50ms SLA at 25,000 TPS peak load.",
            observed_at=day_ago(75),
            metadata={"status": "ACCEPTED", "supersedes": "ADR-001"},
            author="Alex Mercer",
        ),
        SourceRecord(
            id="rec-jira-clara-104",
            source_id="src-jira-aegis",
            source_type=SourceType.JIRA,
            project_id="prj-clara-v3",
            external_id="CLARA-104",
            title="[Feature] PCI-DSS Field-Level Encryption wrapper in auth service",
            content="Implement AES-256 GCM client-side encryption for sensitive fields before caching in Redis or publishing. Assigned to Rakesh Reddy.",
            observed_at=day_ago(2),
            metadata={"status": "IN_PROGRESS", "priority": "HIGH", "assignee": "Rakesh Reddy"},
            author="Sarah Jenkins",
        ),
        SourceRecord(
            id="rec-jira-clara-101",
            source_id="src-jira-aegis",
            source_type=SourceType.JIRA,
            project_id="prj-clara-v3",
            external_id="CLARA-101",
            title="[Bug] DB Connection pool leak in authentication service",
            content="Under high load, database connections are not properly returned to the pool during token validation, causing HTTP 500 errors. Priority: Critical.",
            observed_at=day_ago(4),
            metadata={"status": "OPEN", "priority": "CRITICAL", "assignee": "Sarah Jenkins"},
            author="Sarah Jenkins",
        ),
    ]

    # 8. Evidence Items (Linked to Source Records with Authority, Freshness & Conflict Flags)
    evidence_items = [
        Evidence(
            id="evi-jira-108",
            source_record_id="rec-jira-108",
            source_type=SourceType.JIRA,
            source_title="Jira AEGIS-108",
            external_id="AEGIS-108",
            project_id="prj-aegis",
            excerpt="Kafka consumer group rebalances freeze consumption for 1.2 to 2.4s under 18,000 TPS load, directly causing settlement timeouts.",
            authority=AuthorityLevel.HIGH,
            observed_at=hours_ago(6),
            freshness_score=0.98,
            relevance_score=0.96,
            url="https://jira.acmefin.internal/browse/AEGIS-108",
            author="Alex Mercer",
            is_conflicting=False,
        ),
        Evidence(
            id="evi-jira-112",
            source_record_id="rec-jira-112",
            source_type=SourceType.JIRA,
            source_title="Jira AEGIS-112",
            external_id="AEGIS-112",
            project_id="prj-aegis",
            excerpt="QSA auditor finding: cardholder data passing through Kafka partitions requires field-level encryption. Sign-off blocked.",
            authority=AuthorityLevel.HIGH,
            observed_at=day_ago(2),
            freshness_score=0.92,
            relevance_score=0.94,
            url="https://jira.acmefin.internal/browse/AEGIS-112",
            author="Elena Rostova",
            is_conflicting=False,
        ),
        Evidence(
            id="evi-jira-115-conflict",
            source_record_id="rec-jira-115",
            source_type=SourceType.JIRA,
            source_title="Jira AEGIS-115 (Outdated)",
            external_id="AEGIS-115",
            project_id="prj-aegis",
            excerpt="Project launch scheduled for September 15, 2026. All tracks on schedule.",
            authority=AuthorityLevel.MEDIUM,
            observed_at=day_ago(25),
            freshness_score=0.35, # Stale
            relevance_score=0.70,
            url="https://jira.acmefin.internal/browse/AEGIS-115",
            author="Sarah Jenkins",
            is_conflicting=True,
            conflict_summary="Contradicts Git commit b4e19f and latest engineering roadmap which pushed release date to October 30, 2026 (+45 days).",
        ),
        Evidence(
            id="evi-adr-001-text",
            source_record_id="rec-adr-002-doc",
            source_type=SourceType.ADR,
            source_title="ADR-001 (Superseded)",
            external_id="ADR-001",
            project_id="prj-aegis",
            excerpt="Synchronous REST APIs for payment communication. [SUPERSEDED by ADR-002 due to throughput failure at >8k TPS].",
            authority=AuthorityLevel.LOW,
            observed_at=day_ago(110),
            freshness_score=0.20,
            relevance_score=0.65,
            author="Alex Mercer",
            is_superseded=True,
            superseded_by="ADR-002",
        ),
        Evidence(
            id="evi-adr-002-text",
            source_record_id="rec-adr-002-doc",
            source_type=SourceType.ADR,
            source_title="ADR-002 (Active Architecture)",
            external_id="ADR-002",
            project_id="prj-aegis",
            excerpt="Event-Driven Architecture using Apache Kafka & Schema Registry. Decouples ledger, sub-50ms SLA at 25k TPS.",
            authority=AuthorityLevel.HIGH,
            observed_at=day_ago(75),
            freshness_score=0.90,
            relevance_score=0.97,
            url="docs/architecture/decisions/ADR-002.md",
            author="Alex Mercer & Marcus Chen",
            is_conflicting=False,
        ),
        Evidence(
            id="evi-adr-003-text",
            source_record_id="rec-adr-002-doc",
            source_type=SourceType.ADR,
            source_title="ADR-003 (Database Choice)",
            external_id="ADR-003",
            project_id="prj-aegis",
            excerpt="PostgreSQL 16+ with pgvector selected as primary canonical data store and context memory substrate.",
            authority=AuthorityLevel.HIGH,
            observed_at=day_ago(60),
            freshness_score=0.92,
            relevance_score=0.93,
            url="docs/architecture/decisions/ADR-003.md",
            author="Alex Mercer",
            is_conflicting=False,
        ),
        Evidence(
            id="evi-jira-clara-104",
            source_record_id="rec-jira-clara-104",
            source_type=SourceType.JIRA,
            source_title="Jira CLARA-104",
            external_id="CLARA-104",
            project_id="prj-clara-v3",
            excerpt="PCI-DSS Field-Level Encryption implementation wrapper to secure cardholder data.",
            authority=AuthorityLevel.HIGH,
            observed_at=day_ago(2),
            freshness_score=0.95,
            relevance_score=0.92,
            url="https://jira.acmefin.internal/browse/CLARA-104",
            author="Sarah Jenkins",
            is_conflicting=False,
        ),
        Evidence(
            id="evi-jira-clara-101",
            source_record_id="rec-jira-clara-101",
            source_type=SourceType.JIRA,
            source_title="Jira CLARA-101",
            external_id="CLARA-101",
            project_id="prj-clara-v3",
            excerpt="Database connection pool leak causing token validation endpoints to fail with HTTP 500.",
            authority=AuthorityLevel.HIGH,
            observed_at=day_ago(4),
            freshness_score=0.90,
            relevance_score=0.96,
            url="https://jira.acmefin.internal/browse/CLARA-101",
            author="Sarah Jenkins",
            is_conflicting=False,
        ),
    ]

    # 9. 5-Tier Memory Items
    memory_items = [
        MemoryItem(
            id="mem-sem-01",
            org_id=org.id,
            project_id="prj-aegis",
            type=MemoryType.SEMANTIC,
            title="Core SLA Guarantee for Payment Settlement",
            content="All payment transactions in Project Aegis must achieve sub-50ms processing latency at 99.9th percentile up to 25,000 TPS.",
            confidence=0.99,
            validity_from=day_ago(120),
            linked_evidence_ids=["evi-adr-002-text"],
        ),
        MemoryItem(
            id="mem-sem-02",
            org_id=org.id,
            project_id="prj-aegis",
            type=MemoryType.SEMANTIC,
            title="Data Governance: Zero Unencrypted Cardholder Data in Transit",
            content="Cardholder data (PAN/CVV) must strictly use AES-256 envelope encryption via KMS before entering any Kafka stream.",
            confidence=0.99,
            validity_from=day_ago(100),
            linked_evidence_ids=["evi-jira-112"],
        ),
        MemoryItem(
            id="mem-epi-01",
            org_id=org.id,
            project_id="prj-aegis",
            type=MemoryType.EPISODIC,
            title="Incident INC-892: Kafka Partition Rebalance Storm during Load Test",
            content="On August 14, 2026, synthetic traffic burst triggered consumer timeout cascades. Alex Mercer identified rebalance storms as the root cause, leading to AEGIS-108.",
            confidence=0.95,
            validity_from=day_ago(8),
            linked_evidence_ids=["evi-jira-108", "evi-git-92c4a"],
        ),
        MemoryItem(
            id="mem-pro-01",
            org_id=org.id,
            project_id="prj-aegis",
            type=MemoryType.PROCEDURAL,
            title="High-Impact Production Mutation Approval Policy",
            content="Any change affecting Jira release milestones, Kafka topic partitioning, or production deployment gates requires two-person rule approval with VP/Lead signoff.",
            confidence=0.98,
            validity_from=day_ago(150),
            linked_evidence_ids=[],
        ),
        MemoryItem(
            id="mem-dec-01",
            org_id=org.id,
            project_id="prj-aegis",
            type=MemoryType.DECISION,
            title="Architectural Migration: REST to Event Sourcing (ADR-001 -> ADR-002)",
            content="Superseded synchronous REST (ADR-001) in favor of Apache Kafka event sourcing (ADR-002) to satisfy 25k TPS scaling requirements.",
            confidence=0.97,
            validity_from=day_ago(75),
            linked_evidence_ids=["evi-adr-001-text", "evi-adr-002-text"],
        ),
        MemoryItem(
            id="mem-exp-01",
            org_id=org.id,
            project_id="prj-aegis",
            type=MemoryType.EXPERIENTIAL,
            title="Historical Resolution Pattern: Partition Rebalance Mitigation",
            content="In Q4 2025 Core Banking migration, similar partition rebalance freezes were resolved by adopting static group membership (KIP-345) and tuning session.timeout.ms to 45000ms.",
            confidence=0.92,
            validity_from=day_ago(200),
            linked_evidence_ids=["evi-git-92c4a"],
        ),
    ]

    # 10. Sample Pending Governed Actions
    pending_actions = [
        ActionPreview(
            id="act-aegis-escalate-108",
            agent_run_id="run-initial-sample",
            tool_name="jira_create_issue",
            target_system="Jira Enterprise (AEGIS Project)",
            summary="Create Jira P0 Escalation: Emergency Kafka Partition Rebalance & Static Membership Deployment",
            description="Create linked sub-task under AEGIS-108 to immediately deploy KIP-345 static consumer membership across all 12 worker nodes and adjust session timeout to 45s.",
            risk_class=RiskClass.HIGH_IMPACT,
            requires_approval=True,
            status=ActionStatus.PENDING_APPROVAL,
            params={
                "project_key": "AEGIS",
                "issue_type": "Task",
                "priority": "P0 Critical",
                "summary": "Deploy KIP-345 Static Consumer Group Membership to Staging & Production",
                "parent_key": "AEGIS-108",
                "assignee": "Alex Mercer",
                "due_date": "2026-08-25",
            },
            diff_preview={
                "target_system": "Jira / AEGIS",
                "operation": "CREATE_ISSUE",
                "parent": "AEGIS-108",
                "priority": "P0 Critical",
            },
            impact_assessment="Will create blocking engineering task in Jira and notify SRE on-call rotation.",
            reversibility="high",
            rationale="Kafka partition rebalance freezes under 18k TPS require immediate KIP-345 static membership deployment to prevent settlement pipeline failures.",
            suggested_by_agent=AgentWorkflow.PROJECT_INTELLIGENCE,
            created_at=hours_ago(2),
        ),
        ActionPreview(
            id="act-aegis-schedule-update",
            agent_run_id="run-initial-sample",
            tool_name="jira_update_issue",
            target_system="Jira Enterprise (AEGIS Project)",
            summary="Update AEGIS-115 Target Date: Reconcile Jira milestone with Git commit b4e19f2a schedule",
            description="Adjust AEGIS-115 target_date from 2026-09-15 to 2026-10-30 based on Git commit b4e19f2a analysis of Kafka partition rebalance timeline.",
            risk_class=RiskClass.HIGH_IMPACT,
            requires_approval=True,
            status=ActionStatus.PENDING_APPROVAL,
            params={
                "issue_key": "AEGIS-115",
                "updates": {
                    "target_date": "2026-10-30",
                    "status": "REVISED_SCHEDULE",
                },
                "comment": "Reconciled schedule with Lead Architect Git commit b4e19f.",
            },
            diff_preview={
                "target_system": "Jira / AEGIS-115",
                "operation": "UPDATE_ISSUE",
                "field": "target_date",
                "from": "2026-09-15",
                "to": "2026-10-30",
            },
            impact_assessment="Will update Jira milestone target date and notify stakeholders of revised schedule.",
            reversibility="high",
            rationale="Git commit b4e19f2a by Lead Architect confirms Kafka partition rebalance remediation extends timeline to 2026-10-30. Jira milestone must be reconciled.",
            suggested_by_agent=AgentWorkflow.PROJECT_INTELLIGENCE,
            created_at=hours_ago(1),
        ),
    ]

    # 11. Initial Audit Events
    audit_events = [
        AuditEvent(
            id="aud-001",
            org_id=org.id,
            actor_id="usr-alex-mercer",
            actor_name="Alex Mercer",
            action_type="ADR_ACCEPTED",
            entity_type="decision",
            entity_id="dec-adr-002",
            policy_result="ALLOWED",
            trace_id="tr-init-001",
            details={"title": "ADR-002 Accepted", "supersedes": "ADR-001"},
            created_at=day_ago(75),
        ),
        AuditEvent(
            id="aud-002",
            org_id=org.id,
            actor_id="system-ecb-sync",
            actor_name="ECB Ingestion Service",
            action_type="SOURCE_SYNC",
            entity_type="source",
            entity_id="src-jira-aegis",
            policy_result="ALLOWED",
            trace_id="tr-sync-002",
            details={"records_synced": 18, "status": "healthy"},
            created_at=hours_ago(1),
        ),
    ]

    return {
        "organization": org,
        "users": users,
        "sources": sources,
        "projects": projects,
        "decisions": decisions,
        "risks": risks,
        "source_records": source_records,
        "evidence_items": evidence_items,
        "memory_items": memory_items,
        "pending_actions": pending_actions,
        "audit_events": audit_events,
    }
